name: Build

on: [ push, pull_request ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ ubuntu-latest, windows-latest, macos-14 ]

    steps:
      - uses: actions/checkout@v5

      - name: Set up msvc on Windows
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.1.4

      - uses: actions/upload-artifact@v4
        with:
          name: artifacts-wheels-${{ matrix.platform }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl